version: '2.1'
services:
    mongodb:
      image: autopilotpattern/mongodb
      command: --replSet=famished_test
      restart: always
      build: .
      environment:
        - MONGO_REPLSET=famished_test
      ports:
        - 27017

    consul:
      image: consul:0.7.5
      command: agent -server -client=0.0.0.0 -bootstrap -ui
      ports:
        - 8500:8500
      restart: always
